# Assignment


<font color = 'red' size = 3>Problem Statement 1 :Write a Python program to multiply a M * N matrix by N * A matrix and create a real matrix product</font>

In [1]:
import numpy as np

In [2]:
# creating M *N Matrix(5*3)

arr1 = np.random.random((5,3))
print("M*N (5*3) Matrix = ")
print(arr1)
print()

# Creating N*A Matrix(3*2)

arr2 = np.random.random((3,2))
print("N*A (3*2) Matrix = ")
print(arr2)
print()

# Multiplying two matrix

Dot_Matrix = np.dot(arr1,arr2)
print("The Real matrix product(Dot_Matrix) = ")
print(Dot_Matrix)


M*N (5*3) Matrix = 
[[0.01440722 0.80048983 0.26235381]
 [0.03005962 0.29423498 0.06781514]
 [0.86916458 0.32968969 0.92621185]
 [0.18825784 0.38675292 0.58002547]
 [0.99293022 0.09787782 0.21223781]]

N*A (3*2) Matrix = 
[[0.99655322 0.13451172]
 [0.09294089 0.01270142]
 [0.03675642 0.50173385]]

The Real matrix product(Dot_Matrix) = 
[[0.09839899 0.14373709]
 [0.05979512 0.04180573]
 [0.93085465 0.58581219]
 [0.24487378 0.32125361]
 [1.00640576 0.24129083]]



<font color= 'red' size = 3>Problem Statement 2 :Write a NumPy program to check if each element of an array of your choice is composed of digits, 
lower case letters, and upper case letters only.</font>

In [3]:
array = np.array(["C++","java","NET","Maths", 9 ,"LOGIC", 89])
print("array = ",array)
print()

x = np.char.isdigit(array)
y = np.char.islower(array)
z = np.char.isupper(array)

print("Digits only = ", x)
print()
print("lowercase only = ", y)
print()
print("Uppercase only = ", z)


array =  ['C++' 'java' 'NET' 'Maths' '9' 'LOGIC' '89']

Digits only =  [False False False False  True False  True]

lowercase only =  [False  True False False False False False]

Uppercase only =  [ True False  True False False  True False]



<font color='red' size = 3>Problem Statement 3 :Write a program thatreads two space-separated positive integers X and Y as input and perform the
following tasks </font>

In [13]:
print("Enter the Two positive number X Y : ")
X,Y= input().split()
print("X : ",int(X))
print("Y : ",int(Y))

Enter the Two positive number X Y : 
2 3
X :  2
Y :  3


<font color='blue' size=3>Create a list (lst1) starting at one (1) with 16 elements at a step of X</font>

In [15]:
lst1 = np.arange(1,32,2)
print("lst1 : ",lst1)

lst1 :  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]


<font color='blue' size=3>Create a list (lst2) starting at one (1) with 16 elements at a step of Y</font>

In [18]:
lst2 = np.arange(1,48,3)
print("lst2 : ",lst2)

lst2 :  [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46]


<font color='blue' size=3>Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively</font>

In [25]:
np1 = np.array(lst1)
np2 = np.array(lst2)
print("np1 : ",np1 ,"np2 :", np2)

np1 :  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31] np2 : [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46]


<font color='blue' size =3>Reshape both the NumPy arrays to (4,4)</font>

In [31]:
print("np1 : ")
print(np1.reshape(4,4))
print()
print("np2 : ")
print(np2.reshape(4,4))

np1 : 
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]

np2 : 
[[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]
 [37 40 43 46]]


<font color='blue' size =3>Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)</font>

In [36]:
# np3 = np.subtract(np1,np2)
np3 = np1 - np2
print("np3 : ")
print(np3)

np3 : 
[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


<font color='blue' size=3>Print all the elements of np3 in a single dimension list like the format </font>

In [37]:
print(np3)

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


<font color='red' size = 3>problem statement 4 :
    Write a Python program thattakes two integer-NumPy arrays, P and Q of shape [3∗3]and performthe following task</font>

In [64]:
P = np.array([[23,6,12],[34,32,13],[8,16,26]])
Q = np.array([[12,3,10],[21,5,11],[14,9,22]])
print("P : ")
print(P)
print("Q : ")
print(Q)

P : 
[[23  6 12]
 [34 32 13]
 [ 8 16 26]]
Q : 
[[12  3 10]
 [21  5 11]
 [14  9 22]]


<font color='blue' size=3>Print the element-wise difference of the matrix P and Q(P−Q)</font>

In [65]:
Difference = np.subtract(P,Q)
print("Difference")
print(Difference)

Difference
[[11  3  2]
 [13 27  2]
 [-6  7  4]]
